//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsCategoria.SVC_Categorias {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceCategoria")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVC_Categorias.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCategoria", ReplyAction="http://tempuri.org/IService1/getCategoriaResponse")]
        string getCategoria(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCategoria", ReplyAction="http://tempuri.org/IService1/getCategoriaResponse")]
        System.Threading.Tasks.Task<string> getCategoriaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditCategoria", ReplyAction="http://tempuri.org/IService1/EditCategoriaResponse")]
        string EditCategoria(int id, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditCategoria", ReplyAction="http://tempuri.org/IService1/EditCategoriaResponse")]
        System.Threading.Tasks.Task<string> EditCategoriaAsync(int id, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategoria", ReplyAction="http://tempuri.org/IService1/DeleteCategoriaResponse")]
        string DeleteCategoria(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategoria", ReplyAction="http://tempuri.org/IService1/DeleteCategoriaResponse")]
        System.Threading.Tasks.Task<string> DeleteCategoriaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CriarCategoria", ReplyAction="http://tempuri.org/IService1/CriarCategoriaResponse")]
        string CriarCategoria(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CriarCategoria", ReplyAction="http://tempuri.org/IService1/CriarCategoriaResponse")]
        System.Threading.Tasks.Task<string> CriarCategoriaAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WindowsFormsCategoria.SVC_Categorias.CompositeType GetDataUsingDataContract(WindowsFormsCategoria.SVC_Categorias.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WindowsFormsCategoria.SVC_Categorias.CompositeType> GetDataUsingDataContractAsync(WindowsFormsCategoria.SVC_Categorias.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsCategoria.SVC_Categorias.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsCategoria.SVC_Categorias.IService1>, WindowsFormsCategoria.SVC_Categorias.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getCategoria(int id) {
            return base.Channel.getCategoria(id);
        }
        
        public System.Threading.Tasks.Task<string> getCategoriaAsync(int id) {
            return base.Channel.getCategoriaAsync(id);
        }
        
        public string EditCategoria(int id, string value) {
            return base.Channel.EditCategoria(id, value);
        }
        
        public System.Threading.Tasks.Task<string> EditCategoriaAsync(int id, string value) {
            return base.Channel.EditCategoriaAsync(id, value);
        }
        
        public string DeleteCategoria(int id) {
            return base.Channel.DeleteCategoria(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCategoriaAsync(int id) {
            return base.Channel.DeleteCategoriaAsync(id);
        }
        
        public string CriarCategoria(string value) {
            return base.Channel.CriarCategoria(value);
        }
        
        public System.Threading.Tasks.Task<string> CriarCategoriaAsync(string value) {
            return base.Channel.CriarCategoriaAsync(value);
        }
        
        public WindowsFormsCategoria.SVC_Categorias.CompositeType GetDataUsingDataContract(WindowsFormsCategoria.SVC_Categorias.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsCategoria.SVC_Categorias.CompositeType> GetDataUsingDataContractAsync(WindowsFormsCategoria.SVC_Categorias.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
